---
title: "Project_v1"
output: pdf_document
---

# Things to Try # 

```{r, include = FALSE}
#libraries used
library(astsa)
library(car)
library(fGarch)
library(forecast)
library(ggplot2)
library(KernSmooth)
library(lubridate)
library(readr)
library(rugarch)
library(tseries)
library(TSA)
library(xtable)
library(xts)

```


## Here we process the data ##

We create 3 transformations of our original data `Beijing`:

1. $\log(Y_{t})$
2. $D\log(Y_{t})$
3. $D^{2}\log(Y_{t})$

```{r, include = FALSE}
#####################################Read data
#####################################
Beijing <-read_csv("~/Desktop/Semestre 2/7. Time Series/Project/beijing23 - Sheet1.csv")

######################################convert data to time series object
Beijing.ts <- ts(Beijing$AQI)
#####################################transformations
Beijing.log <- log(Beijing.ts)
Beijing.log.diff <- diff(Beijing.log)
Beijing.log.diff.diff= diff(Beijing.log.diff, lag = 365)

#####################################plot the Y_{t} data
par(mfrow = c(1, 3),pty = "s")
plot(Beijing.ts,main = "Original Dataset: Plot", xlab = "Time", ylab = "AQI")
acf(Beijing.ts, main = "Original Dataset: ACF")
pacf(Beijing.ts, main = "Original Dataset: PACF")

#kpss test
kpss.test(Beijing.ts)

#####################################plot diff(log(Y_{t})) data
par(mfrow = c(1, 3),lheight = 1,pty = "s")

#acf
plot(Beijing.log.diff,main = "Logdiff Dataset: Plot")
acf(Beijing.log.diff, main = "Logdiff Dataset: ACF", lag.max = 1000)
points(c(365, 730), c(0.1,0.1), pch = 22, col = 'red')
pacf(Beijing.log.diff, main = "Logdiff Dataset: PACF", lag.max = 1000)

#kpss test
kpss.test(Beijing.log.diff)

```

# Functions #

```{r}
#functions to estimate the variance
##function to approximate the variance using a window of length 5
##assuming that the variance in the variance is over 365 days
window_func <- function(m, data) {
  Y <- rep(0, 365 / m)
  Z  <- rep(0 , 365)
  y1 <- data[1:365]^2
  y2 <- data[366:730]^2
  y3 <- data[731:1095]^2
  
  for (i in 1:(365 / m)){
    
    pivot <- (i - 1) * m + 1
    Y[i] <- sum(y1[pivot:(pivot + m - 1)]) + sum(y2[pivot:(pivot + m - 1)]) + sum(y3[pivot:(pivot + m - 1)])
    Z[pivot:(pivot + m - 1)] <- rep(Y[i],m)
  }
  
  Z / (3 * m - 1)
  
}
##assuming that the variance in the variance is over 300 days
window_func.300 <- function(m, data) {
  Y = rep(0, 300 / m)
  Z  = rep(0, 300)
  y1 <- data[1:300]^2
  y2 <- data[301:600]^2
  y3 <- data[601:900]^2
  
  for (i in 1:(300 / m)){
    
    pivot <- (i - 1) * m + 1
    Y[i] <- sum(y1[pivot:(pivot + m - 1)]) + sum(y2[pivot:(pivot + m - 1)]) + sum(y3[pivot:(pivot + m - 1)])
    Z[pivot:(pivot + m - 1)] <- rep(Y[i],m)
  }
  
  Z / (3 * m - 1)
  
}

#Box-Jung Dr. Thibaud's code modified
box.jung <- function(model, p, q){

  e <- model$residuals
  lbt <- c()
  m <- p + q + 1
  for (h in m:50) {
  lbt[h] <- Box.test(e, lag=h, type='Ljung-Box', fitdf=(p + q))$p.value
  }
  plot(m:50, lbt[m:50], ylim=c(0,1), xlab='DF', ylab='p value')
  abline(h=0.05,col = 'blue',lty = 'dotted')
    
}

#aic_table from Leo Belzile
aic_table <- function(data, P, Q) {
    table <- matrix(NA, (P + 1), (Q + 1))
    for (p in 0:P) {
        for (q in 0:Q) {
            table[p + 1, q + 1] <- Arima(data, order = c(p, 1, q))$aic
        }
    }
    dimnames(table) <- list(paste("<b> AR", 0:P, "</b>", sep = ""), paste("MA", 
        0:Q, sep = ""))
    table
}
```

# Forecasting #

##Assuming variance of 365 days##

### `Beijing.ts` ###

```{r}
#window of 5
st_dev.1 <- sqrt(window_func(5, Beijing.ts))

stabseries.1 <- Beijing.ts / c(rep(st_dev.1, 3), st_dev.1[1:30])

plot(stabseries.1)
acf(stabseries.1)
pacf(stabseries.1)

#check if the differenced time series is stationary
plot(diff(stabseries.1))
kpss.test(diff(stabseries.1))

#fit arima model
model.1 <- Arima(stabseries.1, c(2, 1, 2), method = "ML")
box.jung(model.1, p = 2, q = 2)
qqPlot(model.1$residuals)

#aic table of models
Beijing_aic_table.1 <- aic_table(stabseries.1, 4, 5)
dimnames(Beijing_aic_table.1) <- list(paste0('AR', 0:4), paste0('MA', 0:5))
latex_tab <- xtable::xtable(Beijing_aic_table.1, booktabs = TRUE, caption = 'AIC values for ARMA models for the Lake Huron dataset')
print(latex_tab,booktabs = TRUE, caption.placement = 'top')

#reconstruction of confidence interval
forecast.1 <- forecast(model.1, h = 30) 

mult <- rep(st_dev.1[31:(30 + 30)])

f1 <- c(sapply(forecast.1$lower[,2] * mult, as.numeric))
f2 <- c(sapply(forecast.1$mean * mult, as.numeric))
f3 <- c(sapply(forecast.1$upper[,2] * mult, as.numeric))


length(Beijing.ts[1001:1125])
Prediction <- data.frame(c(c(Beijing.ts[1001:1125]), f2))
Prediction$newcolumn <- c(rep(NA, 125),f3)
colnames(Prediction) <- c("AQI", "U 95%")

x <- seq(1, by = 1, length = 155)
y <- Prediction$AQI
U <- Prediction$`U 95%`


ggplot(Prediction, aes(x,y)) + geom_path() + 
geom_ribbon(data = Prediction, 
              aes(x = x, y = y, ymin = 0, ymax = U), 
              color= "blue", alpha = .3)

#ar
polyroot(c(1, -coef(model.1)[grep("^ar", names(model.1$coef))]))
#ma
polyroot(c(1, coef(model.1)[grep("^ma", names(model.1$coef))]))

```

## Estimate the Variance $DIFF(LOG(Y_{t}))$ Data ##

- 1124
- 1 to 1095
- 365/5 = 73
- We assumed stationarity

```{r, include=FALSE}
#m = 5
st_dev.2 <- sqrt(window_func(5, Beijing.log))
stabseries.log <- Beijing.log / c(rep(st_dev.2, 3), st_dev.2[1:29])

par(mfrow = c(1, 3))
plot(diff(stabseries.log))
acf(diff(stabseries.log))
pacf(diff(stabseries.log))

model.stabseries.log <- Arima(stabseries.log, c(2, 1, 2), method = "ML")

box.jung(model.stabseries.log, p = 1, q = 2)
cpgram(model.stabseries.log$residuals)
qqPlot(model.stabseries.log$residuals)

Beijing_aic_table.2 <- aic_table(stabseries.log, 4, 5)
dimnames(Beijing_aic_table.2) <- list(paste0('AR', 0:4), paste0('MA', 0:5))
latex_tab <- xtable::xtable(Beijing_aic_table.2, booktabs = TRUE, caption = 'AIC values for ARMA models for the Lake Huron dataset')
print(latex_tab,booktabs = TRUE, caption.placement = 'top')


#prediction
h <- 59
forecast.log <- forecast(model.stabseries.log, h = h) 

f1 <- c(sapply(forecast.log$lower[,2], as.numeric))
f2 <- c(sapply(forecast.log$mean, as.numeric))
f3 <- c(sapply(forecast.log$upper[,2], as.numeric))


forecast <- exp(f2 * st_dev.2[30:88])
forecast.upper <- exp(f3 * st_dev.2[30:88])

Prediction <- data.frame(c(c(Beijing.ts[500:1125]), forecast))
Prediction$newcolumn <- c(rep(NA, 626),forecast.upper)
colnames(Prediction) <- c("AQI", "U 95%")

x <- seq(1, by = 1, length = 626 + h)
y <- Prediction$AQI
U <- Prediction$`U 95%`

ggplot(Prediction, aes(x,y)) + geom_path() + 
geom_ribbon(data = Prediction, 
              aes(x = x, y = y, ymin = 0, ymax = U), 
              color= "blue", alpha = .3)  
 
#ar
polyroot(c(1, -coef(model.stabseries.log)[grep("^ar", names(model.stabseries.log$coef))]))
#ma
polyroot(c(1, coef(model.stabseries.log)[grep("^ma", names(model.stabseries.log$coef))]))

```

## Assuming variance of 300 days ##

```{r}
st_dev.3 <- sqrt(window_func.300(3, Beijing.ts))

stabseries.3 <- Beijing.ts / c(rep(st_dev.3, 3), st_dev.3[1:225])

plot(stabseries.3)
acf(stabseries.3)
pacf(stabseries.3)

#check if the differenced time series is stationary
plot(stabseries.3)
kpss.test(diff(stabseries.3))

model.sigma.3 <- Arima(stabseries.3, c(2, 1, 3), method = "ML")

box.jung(model.sigma.3, p = 2, q = 3)
qqPlot(model.sigma.3$residuals)

Beijing_aic_table.3 <- aic_table(stabseries.3, 4, 5)
dimnames(Beijing_aic_table.3) <- list(paste0('AR', 0:4), paste0('MA', 0:5))
latex_tab <- xtable::xtable(Beijing_aic_table.3, booktabs = TRUE, caption = 'AIC values for ARMA models for the Lake Huron dataset')
print(latex_tab,booktabs = TRUE, caption.placement = 'top')


#reconstruction of confidence interval

forecast.3 <- forecast(model.sigma.3, h = 100) 

mult <- rep(st_dev.3[31:(30 + 100)])

f1 <- c(sapply(forecast.3$lower[,2] * mult, as.numeric))
f2 <- c(sapply(forecast.3$mean * mult, as.numeric))
f3 <- c(sapply(forecast.3$upper[,2] * mult, as.numeric))


Prediction <- data.frame(c(c(Beijing.ts[500:1125]), f2))
Prediction$newcolumn <- c(rep(NA, 626),f3)
colnames(Prediction) <- c("AQI", "U 95%")

x <- seq(1, by = 1, length = 626 + 100)
y <- Prediction$AQI
U <- Prediction$`U 95%`

ggplot(Prediction, aes(x,y)) + geom_path() + 
geom_ribbon(data = Prediction, 
              aes(x = x, y = y, ymin = 0, ymax = U), 
              color= "blue", alpha = .3)

#ar
polyroot(c(1, -coef(model.sigma.3)[grep("^ar", names(model.sigma.3$coef))]))
#ma
polyroot(c(1, coef(model.sigma.3)[grep("^ma", names(model.sigma.3$coef))]))


```

# Testing #

```{r}

BEIJING02_03 <- read_csv("~/Desktop/BEIJING02-03.csv")
plot(BEIJING02_03$AOTI, type = 'l')

```





